# -*- coding: utf-8 -*-
"""3.K-Nearest Neighbor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S4E1W1JewrNaeEAAvkomlNZZOKQ2TTWy
"""



# import packages
import pandas as pd

#  read data set

df = pd.read_csv("/content/drive/MyDrive/Datasets/diabetes.csv")

# it will construct a data frame

df.head()



# before dividing the data into trainset and test set

# seperate inputs and outputs

#  pregencies ----- age  === featutes or inputs
#  outcome   -------------- output variable / label

x  = df.iloc[ : , 0:8 ]

y  = df.iloc[: , 8]  # df.iloc[: , -1]

# y  = df.iloc[: , -1]

#  df.iloc
# data frame is a two dimension   rows columns
#  df.iloc [ srow : erow , scolumn : ecolumn ]

x

y



#  import package train_test_Split

from sklearn.model_selection import train_test_split

#  pass both inputs and outputs
#  input  train and test
#  output also with tran and test set

x_train , x_test , y_train , y_test =train_test_split(x,y,test_size = 0.2 )    # train_size

# test_size = 0.2   train size = 80   test = 20 %

# test_size = 0.3 train size = 70   test = 30 %

#  x    x_train , x_test
#  y    y_train , y_test

#

# shows size of the dataset with 768 rows and 9 columns
df.shape

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)



from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors=5,p=2,metric='minkowski')

# gini , entrpoy     ===  by default  gini

# training the model
# during training both inputs and ouput

knn_model.fit(x_train,y_train)

# during testing  only inputs

pred = knn_model.predict(x_test)  # y_test

# calculating accuracy
# from sklearn.metrics import accuracy_score
# score = accuracy_score(y_test,pred)
# print(score)

from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

cm = confusion_matrix(y_test, pred)
print("Confusion Matrix:\n", cm)

score = accuracy_score(y_test,pred)
print(score)

# Compute precision
precision = precision_score(y_test,pred)
print("Precision:", precision)

# Compute recall
recall = recall_score(y_test,pred)
print("Recall:", recall)

# Compute F1 score
f1 = f1_score(y_test,pred)
print("F1 Score:", f1)