# -*- coding: utf-8 -*-
"""Linear Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v7WWwmw4R1KUx37JhF9y2JQCJtGRYsZM
"""



from google.colab import drive
drive.mount('/content/drive')

import pandas as pd  # deal with datasets
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

df =pd.read_csv('/content/drive/MyDrive/Datasets/price.csv')
df.head()

# Commented out IPython magic to ensure Python compatibility.


# %matplotlib inline
plt.xlabel('area(sq.ft)')
plt.ylabel('price')
plt.scatter(df.area,df.price,color='red',marker='+')

from sklearn import linear_model
lr = linear_model.LinearRegression()
lr.fit(df[['area']],df.price)

lr.predict([[3300]])

lr.coef_

lr.intercept_

#y=mx+c
135.78767123*3300+180616.43835616432

df1=pd.read_csv('/content/drive/MyDrive/Datasets/areas.csv')
df1.head()

ar=lr.predict(df1)

df1['price']=lr.predict(df1[['area']])
ar = df1['price']

ar.to_csv("areas.csv")
df1.head()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('area(sq.ft)')
plt.ylabel('price')
plt.scatter(df.area,df.price,color='red',marker='+')
plt.plot(df.area,lr.predict(df[['area']]),color='blue')

"""# New Section"""