# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LotJabVSDkMLkmDLd5-ayMtkG2JuKqQW
"""



import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()

dir(iris)

iris.feature_names

df= pd.DataFrame(iris.data, columns=iris.feature_names)
df.head()

# to append target column to data table
df['target'] = iris.target
df.head()

iris.target_names

# o --> setosa , 1--> versicolor  2--->virginica

df.info()

df[df.target==0].head()

# From column we are going to generate another column  by using apply function in that lamda is a small function for transform that you can apply on target column
# We use lamda function to transform to create a new column using apply

df['flower_name'] = df.target.apply(lambda x: iris.target_names[x])
df.head()

# Commented out IPython magic to ensure Python compatibility.
from matplotlib import pyplot as plt
# %matplotlib inline

df0 = df[df.target==0]
df1 = df[df.target==1]
df2 = df[df.target==2]

df2.head()

# Its 2D plot so we are using 2 features
plt.xlabel('sepal length (cm)')
plt.ylabel('sepal width (cm)')
plt.scatter(df0['sepal length (cm)'], df0['sepal width (cm)'], color='green', marker='+')
plt.scatter(df1['sepal length (cm)'], df1['sepal width (cm)'], color='red', marker='*')

# Its 2D plot so we are using 2 features
plt.xlabel('petal length (cm)')
plt.ylabel('petal width (cm)')
plt.scatter(df0['petal length (cm)'], df0['petal width (cm)'], color='green', marker='+')
plt.scatter(df1['petal length (cm)'], df1['petal width (cm)'], color='red', marker='*')

from sklearn.model_selection import train_test_split
x=df.drop(['target','flower_name'], axis='columns')
x

y=df.target
y

x.train, x.test, y.train, y.test = train_test_split(x,y, test_size=0.2)

len(x.train)

len(x.test)

from sklearn.svm import SVC
model = SVC()

#model = SVC(kernel='linear')

model.fit(x.train, y.train)

model.score(x.test, y.test)