# -*- coding: utf-8 -*-
"""K=clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19QeqDFK4m6V1yAvuxSRQgQYUeUcpwaVT
"""



# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler
# %matplotlib inline

df=pd.read_csv('/content/drive/MyDrive/Datasets/Income.csv')
df.head()

plt.scatter(df.Age,df.Income)

km=KMeans(n_clusters=3)
km

y_predicted=km.fit_predict(df[['Age','Income']])
y_predicted

df['cluster']=y_predicted
df.head()

df1= df[df.cluster==0]
df2= df[df.cluster==1]
df3= df[df.cluster==2]

plt.scatter(df1.Age,df1.Income,color='green')
plt.scatter(df2.Age,df2.Income,color='red')
plt.scatter(df3.Age,df3.Income,color='black')

plt.xlabel('Age')
plt.ylabel('Income')
plt.legend()

scaler=MinMaxScaler()
scaler.fit(df[['Income']])
df['Income']=scaler.transform(df[['Income']])
df.head()

#do for the age fearture

scaler=MinMaxScaler()
scaler.fit(df[['Age']])
df['Age']=scaler.transform(df[['Age']])
df.head()

km=KMeans(n_clusters=3)
y_predicted=km.fit_predict(df[['Age','Income']])
y_predicted

df['cluster'] = y_predicted
#df.drop(['cluster'],axis='columns',inplace=True)
df

df1= df[df.cluster==0]
df2= df[df.cluster==1]
df3= df[df.cluster==2]

plt.scatter(df1.Age,df1.Income,color='green')
plt.scatter(df2.Age,df2.Income,color='red')
plt.scatter(df3.Age,df3.Income,color='black')


plt.legend()

km.cluster_centers_

df1= df[df.cluster==0]
df2= df[df.cluster==1]
df3= df[df.cluster==2]

plt.scatter(df1.Age,df1.Income,color='green')
plt.scatter(df2.Age,df2.Income,color='red')
plt.scatter(df3.Age,df3.Income,color='black')

plt.scatter(km.cluster_centers_[:,0],km.cluster_centers_[:,1],color='purple',marker='*',label='centroid')


plt.legend()